### ISSUE TITLE
the project name was already in use since two years...

### ISSUE THREAD

**Issue by stax76** [hudec117/Mpv.NET.lib#5]
the project name was already in use since two years...

https://github.com/stax76/mpv.net

**Comment by hudec117** [comment]
Hi,

I'll look into what I can rename the project to. In the meantime, any ideas?

**Comment by stax76** [comment]
My player is more or less finished and I'm happy with it except I would like to have python scripting using the latest cpython, unfortunately I'm not good in python and C++ so it's gonna be hard if I follow that goal.

What are your goals? It seems there is quite a bit work to do to make it a complete player, I only found two samples that hardly do anything except playing a file. Are you gonna use winforms or wpf or something else?

**Comment by hudec117** [comment]
My player was not created to be a full usable application like yours. It's meant to be used more like an API - providing an easy way to introduce a video player into other people's applications. More like a re-usable component/user control.

Because of this distinction, it would probably be appropriate to rename my project so it does not clash with yours, any ideas on what it could be called?

**Comment by stax76** [comment]
libmpv.net?

**Comment by hudec117** [comment]
Yeah something along those lines. I'll assess what will have to be changed and start making changes as soon as I have time.

**Comment by stax76** [comment]
You can rename your project in the project settings.

https://github.com/stax76/mpv.net/issues/18

**Comment by hudec117** [comment]
Hiya @stax76, I've renamed the project. Unfortunately I cannot rename the nuget package as those are immutable. I will also add a note to the README for your project.

**Comment by hudec117** [comment]
Hello @stax76, are you satisfied with this?

**Comment by stax76** [comment]
Hi, it's OK.
